bar/urls.py
# bar/urls.py
from django.urls import path
from .views import DashboardView, CreateCategoryView,DrinkDetailView,UpdateDrinkView, DownloadPDFView, DeleteDrinkView,  AllCategoriesView, AddDrinkView, DrinkListView, CartView, TransactionView, CreateOrderView, CompleteTransactionView, ViewInvoiceView, AllInvoicesView,  AddDrinkQuantityView, ReduceDrinkQuantityView


urlpatterns = [

    path('dashboard/', DashboardView.as_view(), name='dashboard'),

    path('drinks/', DrinkListView.as_view(), name='drink_list'),
    path('drinks/<int:pk>/', DrinkDetailView.as_view(), name='drink_detail'),
    path('drinks/<int:pk>/delete/', DeleteDrinkView.as_view(), name='delete_drink'),  # Add the URL pattern for delete view
    path('drinks/<int:pk>/update/', UpdateDrinkView.as_view(), name='update_drink'),  # Add the URL pattern for update view

    path('cart/', CartView.as_view(), name='cart'),
    path('transaction/', TransactionView.as_view(), name='transaction'),
    path('create_order/', CreateOrderView.as_view(), name='create-order'),

    path('complete_transaction/', CompleteTransactionView.as_view(), name='complete_transaction'),
    path('view_invoice/<int:invoice_id>/', ViewInvoiceView.as_view(), name='view_invoice'),
    path('view_invoice/<int:invoice_id>/', ViewInvoiceView.as_view(), name='view_invoice'),  # Add this line
    path('all_invoices/', AllInvoicesView.as_view(), name='all_invoices'),  # Add this line for AllInvoicesView
    path('add_drink_quantity/<int:drink_id>/', AddDrinkQuantityView.as_view(), name='add_drink_quantity'),
    path('reduce_drink_quantity/<int:drink_id>/', ReduceDrinkQuantityView.as_view(), name='reduce_drink_quantity'),


    path('create_category/', CreateCategoryView.as_view(), name='create_category'),  # Add this line
    path('add_drink/', AddDrinkView.as_view(), name='add_drink'),  # Add this line
    path('all_categories/', AllCategoriesView.as_view(), name='all_categories'),  # Add this line for AllCategoriesView


    path('download_pdf/', DownloadPDFView.as_view(), name='download_pdf'),
    
   
    
    
]

omarandblasius/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bar.urls')),
    path('site-administrator/', include('site_administrator.urls')),
]

bar/models.py
# bar/models.py
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Drink(models.Model):
    name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    quantity_in_stock = models.PositiveIntegerField(default=0)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    

class DrinkHistory(models.Model):
    drink = models.ForeignKey(Drink, on_delete=models.CASCADE)
    action = models.CharField(max_length=20)  # "ADD" or "REDUCE"
    quantity_changed = models.IntegerField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.action} {self.quantity_changed} for {self.drink.name} at {self.timestamp}"

class Order(models.Model):
    drink = models.ForeignKey(Drink, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)  # Allow null and blank

    def __str__(self):
        return f"{self.quantity} x {self.drink.name} - Total: {self.total_price}"

class Transaction(models.Model):
    transaction_date = models.DateTimeField(auto_now_add=True)
    orders = models.ManyToManyField(Order)
    total_amount = models.DecimalField(max_digits=8, decimal_places=2)

class Invoice(models.Model):
    transaction = models.OneToOneField(Transaction, on_delete=models.CASCADE)
    invoice_date = models.DateTimeField(auto_now_add=True)
    # Add other fields for customer details if needed

bar/forms.py
# bar/forms.py

from django import forms
from .models import Drink, Category

class DrinkForm(forms.ModelForm):
    class Meta:
        model = Drink
        fields = ['name', 'price', 'quantity_in_stock', 'category']  # Include 'category' field

class DrinkFilterForm(forms.Form):
    name = forms.CharField(label='Filter by Name', required=False)
    category = forms.ModelChoiceField(label='Filter by Category', queryset=Category.objects.all(), required=False)

bar/views.py
# bar/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.views import View
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas  # Add this import statement
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db import models
from .models import Category, Drink, Order, Transaction, Invoice, DrinkHistory
from .forms import DrinkForm ,  DrinkFilterForm 



class DashboardView(View):
    template_name = 'dashboard.html'

    def get(self, request):
        # Calculate total sales
        total_sales = Transaction.objects.aggregate(total_sales=models.Sum('total_amount'))['total_sales'] or 0

        # Get top-selling drinks based on quantity sold
        top_selling_drinks = Drink.objects.annotate(quantity_sold=models.Sum('order__quantity')).order_by('-quantity_sold')[:5]

        # Get available inventory
        available_inventory = Drink.objects.all()

        return render(request, self.template_name, {
            'total_sales': total_sales,
            'top_selling_drinks': top_selling_drinks,
            'available_inventory': available_inventory,
        })
    
class DrinkListView(View):
    template_name = 'drink_list.html'

    def get(self, request):
        # Retrieve all drinks by default
        drinks = Drink.objects.all()

        # Get the filter form
        form = DrinkFilterForm(request.GET)

        if form.is_valid():
            # Apply filters if form is submitted
            name = form.cleaned_data.get('name')
            category = form.cleaned_data.get('category')

            if name:
                drinks = drinks.filter(name__icontains=name)

            if category:
                drinks = drinks.filter(category=category)

        # Add pagination
        paginator = Paginator(drinks, 10)  # Show 10 drinks per page
        page = request.GET.get('page')
        try:
            drinks = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver the first page.
            drinks = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver the last page of results.
            drinks = paginator.page(paginator.num_pages)

        return render(request, self.template_name, {'drinks': drinks, 'form': form})
    

class DrinkDetailView(View):
    template_name = 'drink_detail.html'

    def get(self, request, pk):
        # Get the drink object
        drink = get_object_or_404(Drink, pk=pk)
        return render(request, self.template_name, {'drink': drink})

    def post(self, request, pk):
        # Get the drink object
        drink = get_object_or_404(Drink, pk=pk)
        form = DrinkForm(request.POST, instance=drink)
        
        if form.is_valid():
            # Record the drink quantity change in DrinkHistory
            new_quantity = form.cleaned_data['quantity_in_stock']
            old_quantity = drink.quantity_in_stock
            if new_quantity != old_quantity:
                action = "ADD" if new_quantity > old_quantity else "REDUCE"
                quantity_changed = abs(new_quantity - old_quantity)
                DrinkHistory.objects.create(drink=drink, action=action, quantity_changed=quantity_changed)

            form.save()
            return redirect('drink_detail', pk=pk)

        return render(request, self.template_name, {'drink': drink, 'form': form})

    
class UpdateDrinkView(View):
    template_name = 'drink_update.html'

    def get(self, request, pk):
        # Get the drink object to be updated
        drink = get_object_or_404(Drink, pk=pk)
        form = DrinkForm(instance=drink)
        return render(request, self.template_name, {'form': form})

    def post(self, request, pk):
        # Get the drink object to be updated
        drink = get_object_or_404(Drink, pk=pk)
        form = DrinkForm(request.POST, instance=drink)
        
        if form.is_valid():
            form.save()
            return redirect('drink_list')

        return render(request, self.template_name, {'form': form})
    
class DeleteDrinkView(View):
    template_name = 'drink_confirm_delete.html'

    def get(self, request, pk):
        # Get the drink object to be deleted
        drink = get_object_or_404(Drink, pk=pk)
        return render(request, self.template_name, {'drink': drink})

    def post(self, request, pk):
        # Get the drink object to be deleted
        drink = get_object_or_404(Drink, pk=pk)

        # Perform the deletion
        drink.delete()

        # Redirect to the drink list after successful deletion
        return redirect('drink_list')
    
class DownloadPDFView(View):
    def get(self, request):
        # Fetch all drinks from the database
        drinks = Drink.objects.all()

        # Create a PDF file
        response = HttpResponse(content_type='application/pdf')  # Use HttpResponse to send the PDF content
        response['Content-Disposition'] = 'attachment; filename="drink_list.pdf"'  # Set the filename for the download
        p = canvas.Canvas(response, pagesize=letter)

        # Define the font and font size
        font_name = "Helvetica"
        font_size = 12

        # Set the header and footer
        header_text = "Drink List"
        footer_text = "Bar Management System"

        # Position for writing text
        x, y = 100, 800
        line_spacing = 20

        # Write header
        p.setFont(font_name, font_size + 4)
        p.drawString(x, y, header_text)
        y -= line_spacing

        # Write drink details
        p.setFont(font_name, font_size)
        for drink in drinks:
            p.drawString(x, y, f"Drink Name: {drink.name}")
            y -= line_spacing
            p.drawString(x, y, f"Price: ${drink.price:.2f}")
            y -= line_spacing
            p.drawString(x, y, f"Quantity in Stock: {drink.quantity_in_stock}")
            y -= line_spacing
            p.drawString(x, y, "-" * 50)
            y -= line_spacing

        # Write footer
        p.drawString(x, 50, footer_text)

        # Save the PDF file
        p.showPage()
        p.save()

        # Return the HttpResponse
        return response

class AllCategoriesView(View):
    template_name = 'all_categories.html'

    def get(self, request):
        categories = Category.objects.all()
        return render(request, self.template_name, {'categories': categories})

class CreateCategoryView(View):
    template_name = 'create_category.html'

    def post(self, request):
        category_name = request.POST.get('category_name')
        category = Category.objects.create(name=category_name)
        return redirect('drink_list')

    def get(self, request):
        return render(request, self.template_name)

class AddDrinkView(View):
    template_name = 'add_drink.html'

    def post(self, request):
        drink_name = request.POST.get('drink_name')
        drink_price = float(request.POST.get('drink_price', 0))
        drink_quantity = int(request.POST.get('drink_quantity', 0))
        category_id = int(request.POST.get('drink_category'))

        category = Category.objects.get(pk=category_id)

        drink = Drink.objects.create(
            name=drink_name,
            price=drink_price,
            quantity_in_stock=drink_quantity,
            category=category
        )
        return redirect('drink_list')

    def get(self, request):
        categories = Category.objects.all()
        return render(request, self.template_name, {'categories': categories})


    
class CreateOrderView(View):
    template_name = 'create_order.html'

    def get(self, request):
        drinks = Drink.objects.all()
        return render(request, self.template_name, {'drinks': drinks})

    def post(self, request):
        drink_id = request.POST.get('drink_id')
        quantity = int(request.POST.get('quantity', 1))  # Default to 1 if quantity not provided
        drink = Drink.objects.get(pk=drink_id)
        total_price = drink.price * quantity  # Calculate the total price
        order = Order.objects.create(drink=drink, quantity=quantity, total_price=total_price)  # Set the total price
        
        # Add the drink ID to the cart session variable
        cart_items = request.session.get('cart', [])
        cart_items.append(drink.pk)
        request.session['cart'] = cart_items

        return redirect('cart')
    


class AddDrinkQuantityView(View):
    template_name = 'add_drink_quantity.html'

    def post(self, request, drink_id):
        drink = Drink.objects.get(pk=drink_id)
        quantity_to_add = int(request.POST.get('quantity_to_add', 0))
        if quantity_to_add > 0:
            drink.quantity_in_stock += quantity_to_add
            drink.save()
        return redirect('drink_list')

    def get(self, request, drink_id):
        drink = Drink.objects.get(pk=drink_id)
        return render(request, self.template_name, {'drink': drink})

class ReduceDrinkQuantityView(View):
    template_name = 'reduce_drink_quantity.html'

    def post(self, request, drink_id):
        drink = Drink.objects.get(pk=drink_id)
        quantity_to_reduce = int(request.POST.get('quantity_to_reduce', 0))
        if quantity_to_reduce > 0:
            drink.quantity_in_stock -= quantity_to_reduce
            drink.save()
        return redirect('drink_list')

    def get(self, request, drink_id):
        drink = Drink.objects.get(pk=drink_id)
        return render(request, self.template_name, {'drink': drink})
    


class CartView(View):
    template_name = 'cart.html'

    def get(self, request):
        # Retrieve cart items from the session
        cart_items = request.session.get('cart', [])
        drinks = Drink.objects.filter(pk__in=cart_items)

        # Calculate drink_quantity for each drink in the cart
        drink_quantities = {}
        for drink in drinks:
            drink_quantity = cart_items.count(drink.pk)

bar/templates/add_drink.html
<!-- add_drink.html -->

{% extends "base.html" %}

{% block title %}Bar Management System - Add Drink{% endblock %}

{% block content %}
    <h1>Add Drink</h1>
    <form method="post">
        {% csrf_token %}
        <label for="drink_name">Drink Name:</label>
        <input type="text" id="drink_name" name="drink_name" required>
        <label for="drink_price">Price:</label>
        <input type="number" id="drink_price" name="drink_price" step="0.01" required>
        <label for="drink_quantity">Quantity in Stock:</label>
        <input type="number" id="drink_quantity" name="drink_quantity" min="0" required>
        <label for="drink_category">Category:</label>
        <select id="drink_category" name="drink_category" required>
            {% for category in categories %}
                <option value="{{ category.pk }}">{{ category.name }}</option>
            {% endfor %}
        </select>
        <button type="submit" class="btn btn-primary">Add</button>
    </form>
{% endblock %}

bar/templates/add_drink_quantity.html
<!-- add_drink_quantity.html -->

{% extends "base.html" %}

{% block title %}Bar Management System - Add Drink Quantity{% endblock %}

{% block content %}
    <h1>Add Drink Quantity</h1>
    <p>Drink: {{ drink.name }}</p>
    <form method="post">
        {% csrf_token %}
        <label for="quantity_to_add">Quantity to Add:</label>
        <input type="number" id="quantity_to_add" name="quantity_to_add" min="1" required>
        <button type="submit" class="btn btn-primary">Add</button>
    </form>
{% endblock %}

bar/templates/all_invoices.html
<!-- all_invoices.html -->

{% extends "base.html" %}

{% block title %}Bar Management System - All Invoices{% endblock %}

{% block content %}
    <h1>All Invoices</h1>
    <ul>
        {% for invoice in invoices %}
            <li>
                <a href="{% url 'view_invoice' invoice_id=invoice.pk %}">
                    Invoice ID: {{ invoice.pk }} - Transaction Date: {{ invoice.transaction.transaction_date }} - Total Amount: ${{ invoice.transaction.total_amount }}
                </a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

bar/templates/cart.html
{% extends "base.html" %}

{% load custom_filters %}

{% block title %}Bar Management System - Cart{% endblock %}

{% block content %}
<div class="page-header">
    <h3 class="page-title">Your Cart</h3>
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#">Tables</a></li>
        <li class="breadcrumb-item active" aria-current="page"> Drink table </li>
      </ol>
    </nav>
  </div>
  {% if drinks %}
  <table class="table table-striped table-bordered mt-4 mb-2">
      <thead class="thead-dark">
          <tr>
              <th>Name</th>
              <th>Quantity</th>
              <th>Total Price</th>
              <th>Action</th>
          </tr>
      </thead>
      <tbody>
          {% for drink in drinks %}
              <tr>
                  <td>{{ drink.name }}</td>
                  <td>{{ drink_quantities|default_if_none:"{}"|get_item:drink.pk }}</td>
                  <td>
                      ${{ drink.price|floatformat:2 }} * {{ drink_quantities|default_if_none:"{}"|get_item:drink.pk }} =
                      ${{ drink.price|floatformat:2 }} * {{ drink_quantities|default_if_none:"{}"|get_item:drink.pk|add:0 }}
                  </td>
                  <td>
                      <form method="post" class="d-inline">
                          {% csrf_token %}
                          <input type="hidden" name="drink_id_to_remove" value="{{ drink.pk }}">
                          <button type="submit" class="btn btn-danger">Remove</button>
                      </form>
                  </td>
              </tr>
          {% endfor %}
      </tbody>
  </table>
  <form method="post" action="{% url 'complete_transaction' %}">
      {% csrf_token %}
      <button type="submit" class="btn btn-primary">Complete Transaction</button>
  </form>
{% else %}
  <div class="alert alert-info mt-4">
      Your cart is empty.
  </div>
{% endif %}
<p class="mt-4">
  <a class="btn btn-primary" href="{% url 'create-order' %}">Add More Drinks</a>
</p>

<!-- ... (existing content) -->

{% if invoice_id %}
  <p class="mt-4">
      <a class="btn btn-primary" href="{% url 'view_invoice' invoice_id=invoice_id %}">View Invoice</a>
  </p>
{% endif %}


{% endblock %}

bar/templates/complete_transaction.html
<!-- complete_transaction.html -->

{% extends "base.html" %}

{% block title %}Bar Management System - Insufficient Quantity{% endblock %}

{% block content %}
    <h1>Insufficient Quantity</h1>
    <p>The following drinks have insufficient quantity:</p>
    <ul>
        {% for drink in insufficient_drinks %}
            <li>{{ drink.name }} - Available Quantity: {{ drink.quantity_in_stock }}</li>
        {% endfor %}
    </ul>
    <a class="btn btn-primary" href="{% url 'cart' %}">Back to Cart</a>
{% endblock %}

bar/templates/create_category.html
<!-- create_category.html -->

{% extends "base.html" %}

{% block title %}Bar Management System - Create Category{% endblock %}

{% block content %}
    <h1>Create Category</h1>
    <form method="post">
        {% csrf_token %}
        <label for="category_name">Category Name:</label>
        <input type="text" id="category_name" name="category_name" required>
        <button type="submit" class="btn btn-primary">Create</button>
    </form>
{% endblock %}

bar/templates/create_order.html
{% extends "base.html" %}

{% block title %}Bar Management System - Create Order{% endblock %}

{% block content %}
<div class="page-header">
    <h3 class="page-title">Create Order</h3>
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#">Tables</a></li>
        <li class="breadcrumb-item active" aria-current="page"> Drink table </li>
      </ol>
    </nav>
  </div>
  <div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="drink_id">Select Drink:</label>
                    <select class="form-control" name="drink_id" id="drink_id">
                        {% for drink in drinks %}
                            <option value="{{ drink.pk }}">{{ drink.name }} - {{ drink.price }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group">
                    <label for="quantity">Quantity:</label>
                    <input class="form-control" type="number" name="quantity" value="1" min="1">
                </div>
                <button type="submit" class="btn btn-primary">Add to Cart</button>
            </form>
            <p class="mt-3">
                <a class="btn btn-secondary" href="{% url 'drink_list' %}">Back to Drinks List</a>
            </p>
        </div>
    </div>
</div>

    {% endblock %}

bar/templates/drink_confirm_delete.html
<!-- bar/drink_confirm_delete.html -->

{% extends "base.html" %}
{% block title %}Delete Drink{% endblock %}

{% block content %}
    <div class="container mt-5">
        <div class="card">
            <div class="card-body">
                <h1 class="card-title">Confirm Deletion</h1>
                <p class="card-text">Are you sure you want to delete the drink "{{ drink.name }}"?</p>
                <form method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger mr-2">Confirm Delete</button>
                    <a href="{% url 'drink_list' %}" class="btn btn-secondary">Cancel</a>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

bar/templates/drink_detail.html
<!-- bar/drink_detail.html -->

{% extends "base.html" %}
{% load custom_filters %}

{% block title %}{{ drink.name }} - Drink Details{% endblock %}

{% block content %}
    <h1>{{ drink.name }}</h1>
    <p>Price: ${{ drink.price }}</p>
    <p>Quantity in Stock: {{ drink.quantity_in_stock }}</p>
    <p>Category: {{ drink.category }}</p>  <!-- Display the category -->

    <!-- Display drink history -->
    <h3>Drink History:</h3>
    <ul>
        {% for history in drink.drinkhistory_set.all %}
            <li>{{ history }}</li>
        {% endfor %}
    </ul>

    <!-- Add a link to update the drink -->
    <a href="{% url 'update_drink' drink.pk %}" class="btn btn-primary">Update Drink</a>
{% endblock %}

bar/templates/drink_list.html
{% extends "base.html" %}

{% block title %}Bar Management System - Drinks List{% endblock %}

{% block content %}

<div class="page-header">
    <h3 class="page-title">Drink Table</h3>
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#">Tables</a></li>
        <li class="breadcrumb-item active" aria-current="page"> Drink table </li>
      </ol>
    </nav>
  </div>

  <div class="page-header flex-wrap">
    <div class="header-left">
      <button class="btn btn-primary mb-2 mb-md-0 mr-2"> Create new document </button>
      <button class="btn btn-outline-primary mb-2 mb-md-0"> Import documents </button>
      <a class="btn btn-primary" href="{% url 'cart' %}">Go to Cart</a>
      <a class="btn btn-primary" href="{% url 'create_category' %}">Create Category</a>
      <a class="btn btn-primary" href="{% url 'all_categories' %}">All Categories</a>
      <a class="btn btn-primary" href="{% url 'download_pdf' %}" target="_blank">Download PDF</a>
    </div>
    <div class="header-right d-flex flex-wrap mt-md-2 mt-lg-0">
      <div class="d-flex align-items-center">
       
      </div>
      <a href="{% url 'add_drink' %}" class="btn btn-primary mt-2 mt-sm-0 btn-icon-text">
        <i class="mdi mdi-plus-circle"></i> Add Drink</a>
    </div>
  </div>
  <form method="get" class="form-inline mb-4">
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary ml-2">Filter</button>
</form>
<div class="row">
<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Bordered table</h4>
        <p class="card-description"> Add class <code>.table-bordered</code>
        </p>
        <div class="table-responsive">
          <table class="table table-bordered">
            <thead>
              <tr>
                <th>#</th>
                <th>Name</th>
                <th>Category</th>
                <th>Price</th>
                <th>Quantity in Stock</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
                {% for drink in drinks %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ drink.name }}</td>
                    <td>{{ drink.category }}</td>
                    <td>{{ drink.price }}</td>
                    <td>{{ drink.quantity_in_stock }}</td>
                    <td>     <a href="{% url 'add_drink_quantity' drink_id=drink.pk %}">[Add Quantity]</a>
                        <a href="{% url 'reduce_drink_quantity' drink_id=drink.pk %}">[Reduce Quantity]</a>
                        <a href="{% url 'delete_drink' drink.pk %}" class="btn btn-danger">Delete Drink</a>
                        <a href="{% url 'update_drink' drink.pk %}" class="btn btn-primary">Update Drink</a>
                        <a href="{% url 'drink_detail' drink.pk %}" class="btn btn-primary">Detail</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
          </table>
          <div class="pagination mt-4">
            <span class="step-links">
                {% if drinks.has_previous %}
                    <a href="?page=1">&laquo; first</a>
                    <a href="?page={{ drinks.previous_page_number }}">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ drinks.number }} of {{ drinks.paginator.num_pages }}.
                </span>

                {% if drinks.has_next %}
                    <a href="?page={{ drinks.next_page_number }}">next</a>
                    <a href="?page={{ drinks.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
            </span>
        </div>
        </div>
      </div>
    </div>
  </div>
</div> 

    
{% endblock %}

bar/templates/drink_update.html
<!-- bar/drink_form.html -->

{% extends "base.html" %}
{% block title %}Update Drink{% endblock %}

{% block content %}
    <div class="container mt-5">
        <h1>Update Drink</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary mt-2">Update Drink</button>
        </form>
    </div>
{% endblock %}

bar/templates/transaction_complete.html
{% extends "base.html" %}

{% block title %}Bar Management System - Transaction Complete{% endblock %}

{% block content %}
    <h1>Transaction Complete</h1>
    <p>Thank you for your purchase!</p>
    <p>Transaction Date: {{ transaction.transaction_date }}</p>
    <p>Total Amount: {{ transaction.total_amount }}</p>
    <p>
        <a class="btn btn-primary" href="{% url 'invoice' transaction.id %}">View Invoice</a>
    </p>
    <p>
        <a class="btn btn-secondary" href="{% url 'drink-list' %}">Back to Drinks List</a>
    </p>
{% endblock %}

bar/templates/view_invoice.html
<!-- view_invoice.html -->

{% extends "base.html" %}

{% block title %}Bar Management System - Invoice{% endblock %}

{% block content %}
    <h1>Invoice</h1>
    <p>Invoice ID: {{ invoice.pk }}</p>
    <p>Transaction Date: {{ invoice.transaction.transaction_date }}</p>
    <p>Total Amount: ${{ invoice.transaction.total_amount }}</p>
    <h2>Items:</h2>
    <ul>
        {% for order in invoice.transaction.orders.all %}
            <li>{{ order.quantity }} x {{ order.drink.name }} - Total: ${{ order.total_price }}</li>
        {% endfor %}
    </ul>
{% endblock %}